version: '3.5'
services: 
  back:
    environment:
      - FLASK_ENV=development
    image: docker-flask
    container_name: back_flask
    ports: 
      - 5000:5000
    depends_on:
      - front
    volumes:
      - ./server:/app
  front:
    image: react-app
    container_name: front_react
    ports:
      - 3000:3000
    volumes:
      - ./client:/app
  